# Site settings
# These are used to personalize your new site.
title: Carter T. Hinkle # your name here
logo: "/images/csupfp.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Computer-Science (class of 2023)
  <br /><br />
  <a href="/pdfs/resume.pdf">View My Resume (currently music professor resume as a placeholder)</a>
repository: "MintyDoggo/MintyDoggo.github.io"
github_username:  MintyDoggo # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

